### PR TITLE
Update Electron to 0.36.1 and Fix the User-Agent Defines

### PR DESCRIPTION
**Pull request by dgadelha**
This will update Electron to ^0.36.1 (it went to 0.36.9 in my case), to support the userAgent feature mentioned at Issue #1 
[Source](http://stackoverflow.com/questions/35672602/how-to-set-electron-useragent#comment59099422_35672988)
Will also fix the code to support the user-agent change

### CODE REVIEW

**Comment by Bunkerbewohner** [comment]
Thanks! Did it actually allow you to play HiFi streams, though?
At least for me the option is not available, even with the faked UA. :/

screenshot from 2016-03-03 08 47 05

**Comment by Bunkerbewohner** [comment]
It seems to me that [for HiFi streaming NaCl is required](https://support.tidal.com/hc/en-us/articles/202654692-HiFi-Option-is-Greyed-Out-Not-Selectable-), which is not supported by electron, afaik. See https://github.com/atom/electron/issues/835.

Therefore I'm afraid this PR won't have any actual use apart from bumping the electron version. :(

**Comment by dgadelha** [comment]
Can you try setting the two variables I suggested under the 'window' context?

**Comment by Bunkerbewohner** [comment]
I did. I checked out your code and got the results mentioned above. Did it work for you?

**Comment by dgadelha** [comment]
These ones: https://github.com/Bunkerbewohner/tidal-music-linux/issues/1#issuecomment-191529950

**Pull request closed without merging**
